### ISSUE TITLE
Weather Website Displays Incorrect City Data Upon Search

### ISSUE THREAD

**Issue by shahil9728** [nikhilyadvv/clime#1]
### Bug description

I discovered a bug on the website where, upon visiting, it correctly fetches the weather data for the current location. However, when I specifically search for another city, it displays data for a different city than the one I entered.

`Expected:` I expect that when I search for a city, the weather website should display accurate and relevant weather data for that specific city.

### Steps to reproduce the bug

- Visit https://www.clime.live
- Enter the name of a specific city in the search bar.
- Observe that the displayed weather information corresponds to a different city.

### Screenshot

![Screenshot](https://github.com/nikhilyadvv/clime/assets/96991517/dc33a5c5-e3ac-41b9-83f9-e6483dd51104)

**Comment by nikhilyadvv** [comment]
I've acknowledged the issue you reported. The bug occurs when searching for a city. The Geodb API returns latitude and longitude, and the OpenWeather API fetches weather data using this information. However, the city name returned by the OpenWeather API may differ from the one provided by the Geodb API.

This discrepancy arises because the Geodb API only returns city names for populations exceeding 10,000. Consequently, smaller cities are not mapped under the Geodb API, although the OpenWeather API still provides precise weather data for them at that latitude and longitude. As a result, the city name associated with a particular latitude and longitude may not match between the Geodb and OpenWeather APIs.

I'll work on resolving this inconsistency to ensure accurate city data retrieval. 
Thank you for bringing this to my attention.

**Comment by nikhilyadvv** [comment]
Fixed the issue in the latest commit (b1af7d8858722d90f69cf697f72f75b0198d0e49). Feel free to check the updated website at [Clime](https://clime.live)

**What I've changed:**
I introduced a new `useState` variable named `city`. Now, when a user searches for a city, the `city` state is updated with the searched city's name. If no city is searched, the `city` state is set to the user's current location. 

_Importantly,_ this change doesn't imply that the searched city's weather data is incorrect; it displays accurate data. The modification ensures that the city name is set to the user's search query, preventing any confusion for users searching for a city.

Feel free to contact me if there is an issue again, and thank you for your feedback.
